
import { TableSchema, UserRole, User, Permission, AppPreferences, DataRecord, Shortcut } from './types';

export const DEFAULT_MAP_CENTER: [number, number] = [48.8566, 2.3522]; // Paris
export const DEFAULT_ZOOM = 13;

export const FIELD_TYPES = [
  { value: 'text', label: 'Text' },
  { value: 'number', label: 'Number' },
  { value: 'date', label: 'Date' },
  { value: 'boolean', label: 'Checkbox' },
  { value: 'select', label: 'List' }, // Changed from Dropdown to List
];

export const GEO_TYPES = [
  { value: 'none', label: 'None (Table only)' },
  { value: 'point', label: 'Point (Marker)' },
  { value: 'line', label: 'Line (Path)' }, 
  { value: 'polygon', label: 'Polygon (Area)' },
  { value: 'mixed', label: 'Mixed Collection' },
];

export const MAP_DISPLAY_MODES = [
  { value: 'tooltip', label: 'Popup Tooltip' },
  { value: 'dialog', label: 'Modal Dialog' },
];

export const DIALOG_SIZE_PRESETS = [
  { value: 'small', label: 'Small (400px)' },
  { value: 'medium', label: 'Medium (Default)' },
  { value: 'large', label: 'Large (800px)' },
  { value: 'fullscreen', label: 'Fullscreen' },
  { value: 'custom', label: 'Custom Size' },
];

export const CALENDAR_VIEWS = [
  { value: 'dayGridMonth', label: 'Month View' },
  { value: 'timeGridWeek', label: 'Week View' },
  { value: 'timeGridDay', label: 'Day View' },
  { value: 'listWeek', label: 'List View' },
];

export const TIME_ZONES = [
  { value: 'local', label: 'Local System Time' },
  { value: 'UTC', label: 'Coordinated Universal Time (UTC)' },
];

export const SHORTCUT_TYPES = [
  { value: 'map_preset', label: 'Map Preset (Layers & View)' },
  { value: 'data_view', label: 'Data Filter View' },
  { value: 'quick_add', label: 'Quick Add Feature' },
  { value: 'map_search', label: 'Map Search / Filter' },
  { value: 'dashboard_view', label: 'Open Dashboard' },
];

export const SHORTCUT_ICONS = [
  { value: 'Zap', label: 'Lightning' },
  { value: 'Star', label: 'Star' },
  { value: 'MapPin', label: 'Pin' },
  { value: 'Layers', label: 'Layers' },
  { value: 'Search', label: 'Search' },
  { value: 'AlertTriangle', label: 'Alert' },
  { value: 'Tool', label: 'Tool' },
  { value: 'Truck', label: 'Truck' },
];

export const PERMISSIONS_LIST: { value: Permission; label: string; description: string }[] = [
  { value: 'sys_admin', label: 'System Administrator', description: 'Full access to all settings and configurations.' },
  { value: 'manage_users', label: 'Manage Users', description: 'Can create, update, and delete users and roles.' },
  { value: 'manage_schemas', label: 'Manage Configuration', description: 'Can create and modify table schemas and app structure.' },
  { value: 'view_map', label: 'View Map', description: 'Can access the Map tab.' },
  { value: 'edit_map', label: 'Edit Map Layers', description: 'Can add or modify spatial features on the map.' },
  { value: 'view_data', label: 'View Data', description: 'Can access the Data tab tables.' },
  { value: 'edit_data', label: 'Edit Data', description: 'Can add, edit, or delete data records.' },
  { value: 'view_dashboard', label: 'View Dashboard', description: 'Can access the Analytics Dashboard.' },
  { value: 'view_planning', label: 'View Planning', description: 'Can access the Planning/Calendar tab.' },
];

export const INITIAL_ROLES: UserRole[] = [
  {
    id: 'admin_role',
    name: 'Administrator',
    description: 'Full system access',
    isSystem: true,
    permissions: ['sys_admin', 'manage_users', 'manage_schemas', 'view_map', 'edit_map', 'view_data', 'edit_data', 'view_dashboard', 'view_planning']
  },
  {
    id: 'editor_role',
    name: 'Editor',
    description: 'Can manage data and maps',
    isSystem: true,
    permissions: ['view_map', 'edit_map', 'view_data', 'edit_data', 'view_dashboard', 'view_planning']
  },
  {
    id: 'viewer_role',
    name: 'Viewer',
    description: 'Read-only access',
    isSystem: true,
    permissions: ['view_map', 'view_data', 'view_dashboard', 'view_planning']
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    username: 'admin',
    email: 'admin@geonexus.com',
    roleId: 'admin_role',
    createdAt: new Date().toISOString()
  }
];

const opts = (items: string[]) => items.map(i => ({ label: i, value: i }));
// Helper with colors
const optsC = (items: {l: string, c: string}[]) => items.map(i => ({ label: i.l, value: i.l, color: i.c }));

export const INITIAL_SCHEMAS: TableSchema[] = [
  {
    id: '1',
    name: 'Interventions',
    description: 'Field work and maintenance requests',
    geometryType: 'point',
    color: '#ef4444',
    visibleInData: true,
    isDefaultInData: true,
    allowNonSpatialEntry: true,
    visibleInMap: true,
    isDefaultVisibleInMap: true,
    mapDisplayMode: 'tooltip',
    hoverFields: ['title', 'priority'],
    subLayerConfig: {
      enabled: true,
      field: 'priority',
      rules: [
        { value: 'Critical', color: '#ef4444', label: 'Critical' },
        { value: 'High', color: '#f97316', label: 'High' },
        { value: 'Medium', color: '#eab308', label: 'Medium' },
        { value: 'Low', color: '#22c55e', label: 'Low' }
      ]
    },
    planning: {
      enabled: true,
      titleField: 'title',
      startField: 'date',
      defaultView: 'dayGridMonth',
      timeZone: 'local'
    },
    dashboard: {
      enabled: true,
      showTable: true,
      filters: [],
      widgets: [
        { id: 'w1', type: 'pie', field: 'status', title: 'Status Distribution' },
        { id: 'w2', type: 'bar', field: 'priority', title: 'Priority Levels' }
      ]
    },
    fields: [
      { id: 'f1', name: 'title', label: 'Title', type: 'text', required: true, sortable: true, filterable: true },
      { id: 'f2', name: 'priority', label: 'Priority', type: 'select', required: true, options: optsC([{l:'Low', c:'#22c55e'}, {l:'Medium', c:'#eab308'}, {l:'High', c:'#f97316'}, {l:'Critical', c:'#ef4444'}]), sortable: true, filterable: true },
      { id: 'f3', name: 'status', label: 'Status', type: 'select', required: true, options: optsC([{l:'Open', c:'#3b82f6'}, {l:'In Progress', c:'#8b5cf6'}, {l:'Done', c:'#22c55e'}]), sortable: true, filterable: true },
      { id: 'f4', name: 'date', label: 'Due Date', type: 'date', required: false, sortable: true, filterable: true },
    ]
  },
  {
    id: '2',
    name: 'Assets',
    description: 'Physical infrastructure assets',
    geometryType: 'point',
    color: '#3b82f6',
    visibleInData: true,
    visibleInMap: true,
    isDefaultVisibleInMap: true,
    allowNonSpatialEntry: false,
    mapDisplayMode: 'dialog',
    hoverFields: ['type', 'condition'],
    dialogConfig: { size: 'medium' },
    planning: { enabled: false, titleField: '', startField: '' },
    dashboard: { enabled: false, widgets: [] },
    fields: [
      { id: 'a1', name: 'type', label: 'Asset Type', type: 'select', required: true, options: opts(['Lamp Post', 'Bench', 'Trash Can', 'Signage']), sortable: true, filterable: true },
      { id: 'a2', name: 'condition', label: 'Condition', type: 'select', required: true, options: optsC([{l:'New', c:'#22c55e'}, {l:'Good', c:'#84cc16'}, {l:'Fair', c:'#facc15'}, {l:'Poor', c:'#f43f5e'}]), sortable: true, filterable: true },
      { id: 'a3', name: 'installDate', label: 'Install Date', type: 'date', required: true, sortable: true },
      { id: 'a4', name: 'active', label: 'In Service', type: 'boolean', required: false, sortable: true, booleanLabels: { true: 'Active', false: 'Inactive' } },
    ]
  },
  {
    id: '3',
    name: 'Metro Lines',
    description: 'Subway infrastructure lines',
    geometryType: 'line',
    color: '#8b5cf6',
    visibleInData: true,
    visibleInMap: true,
    isDefaultVisibleInMap: true,
    allowNonSpatialEntry: false,
    mapDisplayMode: 'tooltip',
    hoverFields: ['line_name', 'status'],
    planning: { enabled: false, titleField: '', startField: '' },
    dashboard: { enabled: false, widgets: [] },
    fields: [
      { id: 'l1', name: 'line_name', label: 'Line Name', type: 'text', required: true, sortable: true, filterable: true },
      { id: 'l2', name: 'status', label: 'Status', type: 'select', required: true, options: opts(['Operational', 'Construction', 'Closed']), sortable: true, filterable: true },
    ]
  },
  {
    id: '4',
    name: 'Parks',
    description: 'Public green spaces',
    geometryType: 'polygon',
    color: '#22c55e',
    visibleInData: true,
    visibleInMap: true,
    isDefaultVisibleInMap: true,
    allowNonSpatialEntry: false,
    mapDisplayMode: 'tooltip',
    hoverFields: ['name'],
    planning: { enabled: false, titleField: '', startField: '' },
    dashboard: { enabled: false, widgets: [] },
    fields: [
      { id: 'p1', name: 'name', label: 'Park Name', type: 'text', required: true, sortable: true, filterable: true },
      { id: 'p2', name: 'maintenance', label: 'Maintenance Day', type: 'select', required: false, options: opts(['Monday', 'Wednesday', 'Friday']), sortable: true, filterable: true },
    ]
  },
  {
    id: '5',
    name: 'Employees',
    description: 'Staff directory (Non-spatial)',
    geometryType: 'none',
    color: '#64748b',
    visibleInData: true,
    visibleInMap: false,
    isDefaultVisibleInMap: false,
    allowNonSpatialEntry: true,
    mapDisplayMode: 'tooltip',
    planning: { enabled: false, titleField: '', startField: '' },
    dashboard: { enabled: false, widgets: [] },
    fields: [
      { id: 'e1', name: 'fullname', label: 'Full Name', type: 'text', required: true, sortable: true, filterable: true },
      { id: 'e2', name: 'role', label: 'Role', type: 'select', required: true, options: opts(['Technician', 'Manager', 'Driver']), sortable: true, filterable: true },
      { id: 'e3', name: 'hired_date', label: 'Hired Date', type: 'date', required: true, sortable: true },
    ]
  }
];

// Helper to generate today + n days
const getDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const INITIAL_RECORDS: DataRecord[] = [
  // Interventions
  {
    id: 'rec_1',
    tableId: '1',
    geometry: { type: 'Point', coordinates: [48.8584, 2.2945] }, // Near Eiffel Tower
    data: { title: 'Repair Street Light', priority: 'High', status: 'Open', date: getDate(1) },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rec_2',
    tableId: '1',
    geometry: { type: 'Point', coordinates: [48.8606, 2.3376] }, // Near Louvre
    data: { title: 'Pothole Maintenance', priority: 'Medium', status: 'In Progress', date: getDate(3) },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  
  // Assets
  {
    id: 'rec_5',
    tableId: '2',
    geometry: { type: 'Point', coordinates: [48.8566, 2.3522] }, // Center
    data: { type: 'Bench', condition: 'Good', installDate: '2023-05-15', active: true },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rec_6',
    tableId: '2',
    geometry: { type: 'Point', coordinates: [48.8642, 2.3250] }, // Concorde
    data: { type: 'Lamp Post', condition: 'Fair', installDate: '2020-11-20', active: false },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // Metro Lines (LineString)
  {
    id: 'rec_line_1',
    tableId: '3',
    geometry: { 
      type: 'LineString', 
      coordinates: [
        [48.8737, 2.2950], // Etoile
        [48.8718, 2.3007],
        [48.8650, 2.3125],
        [48.8642, 2.3250]  // Concorde
      ] 
    },
    data: { line_name: 'Line 1', status: 'Operational' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rec_line_2',
    tableId: '3',
    geometry: { 
      type: 'LineString', 
      coordinates: [
        [48.8464, 2.3436],
        [48.8534, 2.3488], // Cité
        [48.8582, 2.3483]
      ] 
    },
    data: { line_name: 'Line 4', status: 'Construction' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // Parks (Polygon)
  {
    id: 'rec_poly_1',
    tableId: '4',
    geometry: { 
      type: 'Polygon', 
      coordinates: [
        [48.8630, 2.3260],
        [48.8650, 2.3280],
        [48.8640, 2.3340],
        [48.8615, 2.3320]
      ] 
    },
    data: { name: 'Tuileries Garden', maintenance: 'Friday' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rec_poly_2',
    tableId: '4',
    geometry: { 
      type: 'Polygon', 
      coordinates: [
        [48.8460, 2.3370],
        [48.8480, 2.3372],
        [48.8482, 2.3420],
        [48.8455, 2.3415]
      ] 
    },
    data: { name: 'Luxembourg Gardens', maintenance: 'Wednesday' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // Employees (None)
  {
    id: 'rec_emp_1',
    tableId: '5',
    geometry: null,
    data: { fullname: 'John Doe', role: 'Manager', hired_date: '2021-03-15' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'rec_emp_2',
    tableId: '5',
    geometry: null,
    data: { fullname: 'Alice Smith', role: 'Technician', hired_date: '2022-07-01' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const DEFAULT_PREFERENCES: AppPreferences = {
  theme: 'system',
  language: 'en',
  primaryColor: '#3b82f6' // Default Tailwind blue-500
};

export const INITIAL_SHORTCUTS: Shortcut[] = [
  {
    id: 's1',
    name: 'Interventions View',
    icon: 'Layers',
    color: '#ef4444',
    type: 'map_preset',
    config: {
      layers: ['1', '3'], // Interventions + Metro
      zoom: 14
    }
  },
  {
    id: 's2',
    name: 'Urgent Work',
    icon: 'AlertTriangle',
    color: '#f59e0b',
    type: 'data_view',
    config: {
      tableId: '1', // Interventions
      search: 'High'
    }
  }
];

export const LANGUAGES = [
  { value: 'en', label: 'English' },
  { value: 'fr', label: 'Français' },
  { value: 'es', label: 'Español' },
  { value: 'de', label: 'Deutsch' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.reset': 'Reset',
    'common.done': 'Done',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',

    // Nav
    'nav.map': 'Map',
    'nav.data': 'Data',
    'nav.dash': 'Dash',
    'nav.plan': 'Plan',
    'nav.config': 'Config',
    
    // User Menu & Profile
    'menu.account': 'My Account',
    'menu.profile': 'Profile',
    'menu.settings': 'Configuration',
    'menu.logout': 'Log out',
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account settings and preferences.',
    'profile.info': 'Personal Information',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.prefs': 'Preferences',
    'profile.notifs': 'Email Notifications',
    'profile.notifs_desc': 'Receive updates about system changes.',
    'profile.2fa': 'Two-Factor Authentication',
    'profile.2fa_desc': 'Add an extra layer of security.',
    'profile.enabled': 'Enabled',
    'profile.enable': 'Enable',

    // Login
    'login.title': 'GeoNexus GIS',
    'login.subtitle': 'Spatial Data Management Platform',
    'login.welcome': 'Welcome back',
    'login.instruction': 'Please sign in to your account to continue',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.btn': 'Sign In',
    'login.authenticating': 'Authenticating...',
    'login.error': 'Invalid credentials. Please try again.',

    // Backoffice Sidebar
    'cfg.title': 'Configuration',
    'cfg.tables': 'Tables & Schemas',
    'cfg.map': 'Map Layers',
    'cfg.data': 'Data Views',
    'cfg.plan': 'Planning',
    'cfg.dash': 'Dashboards',
    'cfg.users': 'Users & Security',
    'cfg.shortcuts': 'Shortcuts',
    'cfg.general': 'General Settings',

    // Shortcuts
    'shortcuts.title': 'Shortcuts',
    'shortcuts.subtitle': 'Quick actions accessible from the sidebar.',
    'shortcuts.add': 'Add Shortcut',
    'shortcuts.edit': 'Edit Shortcut',
    'shortcuts.new': 'New Shortcut',
    'shortcuts.name': 'Name',
    'shortcuts.icon': 'Icon',
    'shortcuts.color': 'Color',
    'shortcuts.type': 'Type',
    'shortcuts.config': 'Configuration',
    'shortcuts.no_config': 'No shortcuts configured.',
    'shortcuts.quick_actions': 'Quick Actions',
    'shortcuts.map_preset': 'Visible Layers',
    'shortcuts.data_view': 'Target Table',
    'shortcuts.quick_add': 'Target Table',
    'shortcuts.map_search': 'Filter Layer',
    'shortcuts.dashboard_view': 'Dashboard',

    // General Settings
    'gen.title': 'General Settings',
    'gen.desc': 'Customize the appearance and behavior of the application.',
    'gen.appearance': 'Appearance',
    'gen.appearance.desc': 'Manage theme and branding colors.',
    'gen.theme': 'Theme Mode',
    'gen.theme.light': 'Light',
    'gen.theme.dark': 'Dark',
    'gen.theme.system': 'System',
    'gen.primary': 'Primary Color',
    'gen.localization': 'Localization',
    'gen.localization.desc': 'Set default language and region options.',
    'gen.lang': 'System Language',

    // Users & Roles
    'users.title': 'Users & Security',
    'users.tab_users': 'Users',
    'users.tab_roles': 'Roles',
    'users.accounts': 'User Accounts',
    'users.accounts_desc': 'Manage system access.',
    'users.add': 'Add User',
    'users.edit': 'Edit User',
    'users.new': 'New User',
    'users.save': 'Save User',
    'users.delete_confirm': 'Delete user?',
    'roles.title': 'User Roles',
    'roles.desc': 'Define permission sets.',
    'roles.create': 'Create Role',
    'roles.edit': 'Edit Role',
    'roles.new': 'New Role',
    'roles.name': 'Role Name',
    'roles.permissions': 'Permissions',
    'roles.save': 'Save Role',
    'roles.delete_confirm': 'Delete role?',
    'roles.system': 'System',

    // Schema / Tables
    'schema.title': 'Tables & Schemas',
    'schema.create': 'Create Table',
    'schema.search': 'Search tables...',
    'schema.filter_type': 'Filter by type',
    'schema.all_types': 'All Types',
    'schema.no_results': 'No tables found matching your criteria.',
    'schema.basic_info': 'Basic Info',
    'schema.table_name': 'Table Name',
    'schema.description': 'Description',
    'schema.fields': 'Field Definitions',
    'schema.add_field': 'Add Field',
    'schema.db_name': 'DB Name',
    'schema.label': 'Label',
    'schema.type': 'Type',
    'schema.required': 'Required',
    'schema.sortable': 'Sortable',
    'schema.filterable': 'Filterable',
    'schema.options': 'Options',
    'schema.checked_label': 'Checked Label',
    'schema.unchecked_label': 'Unchecked Label',
    'schema.no_fields': 'No fields defined. Click "Add Field" to start.',
    'schema.data_view': 'Data View',
    'schema.enable_data': 'Enable Data View',
    'schema.default_data': 'Set as Default Data View',
    'schema.allow_non_spatial': 'Allow Non-Spatial Entry',
    'schema.map_view': 'Map Layer',
    'schema.enable_map': 'Enable Map Layer',
    'schema.default_visible': 'Visible by Default',
    'schema.geo_type': 'Geometry Type',
    'schema.color': 'Layer Color',
    'schema.interaction': 'Interaction Mode',
    'schema.dialog_size': 'Dialog Size',
    'schema.width': 'Width',
    'schema.height': 'Height',
    'schema.planning': 'Planning',
    'schema.enable_planning': 'Enable Planning',
    'schema.title_field': 'Event Title Field',
    'schema.start_field': 'Start Date Field',
    'schema.end_field': 'End Date Field (Optional)',
    'schema.default_view': 'Default View',
    'schema.timezone': 'Time Zone',
    'schema.dashboard': 'Dashboard',
    'schema.enable_dashboard': 'Enable Dashboard',
    'schema.dash_title': 'Dashboard Title',
    'schema.default_dash': 'Set as Default Dashboard',
    'schema.show_table': 'Show Data Table below charts',
    'schema.filters': 'Global Dashboard Filters',
    'schema.add_filter': 'Add Filter',
    'schema.select_field': 'Select Field',
    'schema.select_value': 'Select Value',
    'schema.widgets': 'Widgets',
    'schema.add_widget': 'Add Widget',
    'schema.widget_title': 'Widget Title',
    'schema.preview': 'Live Preview',
    'schema.override_title': 'Override Default Configuration?',
    'schema.override_desc': 'The table is currently set as the default.',
    'schema.save': 'Save Schema',
    'schema.options_title': 'Manage List Options',
    'schema.value': 'Value (Stored)',
    'schema.label_disp': 'Label (Displayed)',
    'schema.save_list': 'Save List',

    // Map
    'map.layers': 'Layers',
    'map.visible': 'Visible Layers',
    'map.editing': 'Editing:',
    'map.select': '-- Select Layer --',
    'map.add': 'Add Feature',
    'map.click': 'Click Map',
    'map.noLayers': 'No map layers configured.',
    'map.adv_search': 'Advanced Search',
    'map.target_layer': 'Target Layer',
    'map.attributes': 'Attributes',
    'map.spatial_filter': 'Spatial Filter',
    'map.draw_zone': 'Draw Zone (Box)',
    'map.redraw_zone': 'Redraw Zone (Box)',
    'map.cancel_draw': 'Cancel Drawing',
    'map.zone_active': 'Zone Active',
    'map.results': 'results',
    'map.print_title': 'Print Map',
    'map.format': 'Format & Orientation',
    'map.scale': 'Scale',
    'map.rotation': 'Rotation',
    'map.export_title': 'Title',
    'map.export_desc': 'Description (Optional)',
    'map.print_btn': 'Print',
    'map.pdf_btn': 'Save PDF',
    'map.lat': 'Lat',
    'map.lng': 'Lng',
    'map.new_feature': 'New Feature',
    'map.edit_feature': 'Edit Feature',
    'map.delete_feature': 'Delete Feature',
    'map.delete_confirm': 'Are you sure you want to delete this feature? This action cannot be undone.',
    'map.confirm_delete': 'Confirm Delete',
    'map.feature_updated': 'Feature Updated',
    'map.feature_added': 'Feature Added',
    'map.feature_deleted': 'Feature Deleted',
    'map.export_failed': 'Export Failed',
    'map.import_geojson': 'Import GeoJSON',
    'map.import_success': 'Import Successful',
    'map.import_error': 'Import Failed',
    'map.import_layer_select': 'Select a target layer first',
    'map.import_summary': 'Imported {count} features',
    
    // Import Dialog
    'map.import_title': 'Import Configuration',
    'map.import_mode_existing': 'Add to existing layer',
    'map.import_mode_new': 'Create new layer',
    'map.new_layer_name': 'New Layer Name',
    'map.select_file': 'Select File & Import',

    // Data
    'data.tables': 'Tables',
    'data.search': 'Search records...',
    'data.add': 'Add Record',
    'data.noTables': 'No tables configured for data view.',
    'data.select': 'Select a table to view data',
    'data.noRecords': 'No records found in this table.',
    'data.spatial': 'Spatial Data Table',
    'data.alphanumeric': 'Alphanumeric Table',
    'data.filters': 'Filters',
    'data.toggle_filters': 'Toggle Column Filters',
    'data.add_map': 'Add on Map',
    'data.add_data': 'Add Data Only',
    'data.clear': 'Clear',
    'data.showing': 'Showing',
    'data.to': 'to',
    'data.of': 'of',
    'data.records': 'records',
    'data.create': 'Create New Record',
    'data.edit': 'Edit Record',
    'data.create_desc': 'Add a new entry.',
    'data.edit_desc': 'Update attributes.',
    'data.save': 'Save Changes',
    'data.delete_title': 'Delete Record',
    'data.delete_desc': 'Are you sure you want to delete this record? This action cannot be undone.',
    'data.record_deleted': 'Record Deleted',
    'data.record_added': 'Record Added',
    'data.record_updated': 'Record Updated',
    'data.map_activated': 'Map Activated',
    'data.go_config': 'Go to Configuration > Data View to enable tables.',
    'data.export': 'Export',
    'data.export_csv': 'Export as CSV',
    'data.export_json': 'Export as JSON',
    'data.export_png': 'Export as PNG (Screenshot)',
    'data.export_success': 'Export Successful',

    // Dashboard
    'dash.title': 'Dashboard & Analytics',
    'dash.total': 'Total Records',
    'dash.fields': 'Fields',
    'dash.widgets': 'Widgets Configured',
    'dash.ai': 'AI Insights',
    'dash.generate': 'Generate Report',
    'dash.noDash': 'No dashboards configured.',
    'dash.select': 'Please select a dataset to analyze.',
    'dash.filtered': 'Filtered View',
    'dash.analysis_by': 'Analysis by',
    'dash.no_matches': 'No records matching filters.',
    'dash.showing_50': 'Showing first 50 records.',
    'dash.generate_hint': 'Click "Generate Report" to have Gemini analyze your data and find patterns.',

    // Planning
    'plan.noPlan': 'No planning tables configured.',
    'plan.calendars': 'Calendars',
    'plan.add_event': 'Add Event',
    'plan.toggle_hint': 'Select a calendar to toggle visibility.',
    'plan.select_cal': 'Select Calendar',
    'plan.choose_cal': 'Choose which calendar to add this event to.',
    'plan.hidden': 'Hidden',
    'plan.edit_event': 'Edit Event',
    'plan.new_event': 'New Event',
    'plan.create_event': 'Create Event',
    'plan.update_event': 'Update Event',
    'plan.delete_title': 'Delete Event',
    'plan.delete_desc': 'Are you sure you want to delete this event?',
    'plan.go_config': 'Go to Configuration > Planning to enable tables.',
    'plan.event_created': 'Event Created',
    'plan.event_updated': 'Event Updated',
    'plan.event_deleted': 'Event Deleted',
    'plan.calendar_enabled': 'Calendar Enabled',
  },
  fr: {
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Éditer',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.add': 'Ajouter',
    'common.close': 'Fermer',
    'common.reset': 'Réinitialiser',
    'common.done': 'Terminé',
    'common.confirm': 'Confirmer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.warning': 'Avertissement',
    'common.info': 'Info',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',

    'nav.map': 'Carte',
    'nav.data': 'Données',
    'nav.dash': 'Tableau',
    'nav.plan': 'Agenda',
    'nav.config': 'Config',
    
    'menu.account': 'Mon Compte',
    'menu.profile': 'Profil',
    'menu.settings': 'Configuration',
    'menu.logout': 'Déconnexion',
    'profile.title': 'Profil',
    'profile.subtitle': 'Gérez vos paramètres de compte et vos préférences.',
    'profile.info': 'Informations Personnelles',
    'profile.username': 'Identifiant',
    'profile.email': 'Email',
    'profile.prefs': 'Préférences',
    'profile.notifs': 'Notifications Email',
    'profile.notifs_desc': 'Recevoir des mises à jour sur les changements du système.',
    'profile.2fa': 'Authentification à deux facteurs',
    'profile.2fa_desc': 'Ajouter une couche de sécurité supplémentaire.',
    'profile.enabled': 'Activé',
    'profile.enable': 'Activer',

    'login.title': 'GeoNexus SIG',
    'login.subtitle': 'Plateforme de Gestion de Données Spatiales',
    'login.welcome': 'Bon retour',
    'login.instruction': 'Veuillez vous connecter pour continuer',
    'login.username': 'Identifiant',
    'login.password': 'Mot de passe',
    'login.btn': 'Se connecter',
    'login.authenticating': 'Connexion...',
    'login.error': 'Identifiants invalides. Réessayez.',
    
    'cfg.title': 'Configuration',
    'cfg.tables': 'Tables & Schémas',
    'cfg.map': 'Couches Carte',
    'cfg.data': 'Vues Données',
    'cfg.plan': 'Planification',
    'cfg.dash': 'Tableaux de Bord',
    'cfg.users': 'Utilisateurs & Sécurité',
    'cfg.shortcuts': 'Raccourcis',
    'cfg.general': 'Paramètres Généraux',

    'shortcuts.title': 'Raccourcis',
    'shortcuts.subtitle': 'Actions rapides accessibles depuis la barre latérale.',
    'shortcuts.add': 'Ajouter un raccourci',
    'shortcuts.edit': 'Éditer le raccourci',
    'shortcuts.new': 'Nouveau raccourci',
    'shortcuts.name': 'Nom',
    'shortcuts.icon': 'Icône',
    'shortcuts.color': 'Couleur',
    'shortcuts.type': 'Type',
    'shortcuts.config': 'Configuration',
    'shortcuts.no_config': 'Aucun raccourci configuré.',
    'shortcuts.quick_actions': 'Actions Rapides',
    'shortcuts.map_preset': 'Couches Visibles',
    'shortcuts.data_view': 'Table Cible',
    'shortcuts.quick_add': 'Table Cible',
    'shortcuts.map_search': 'Couche Filtre',
    'shortcuts.dashboard_view': 'Tableau de Bord',

    'gen.title': 'Paramètres Généraux',
    'gen.desc': 'Personnalisez l\'apparence et le comportement de l\'application.',
    'gen.appearance': 'Apparence',
    'gen.appearance.desc': 'Gérer le thème et les couleurs.',
    'gen.theme': 'Mode Thème',
    'gen.theme.light': 'Clair',
    'gen.theme.dark': 'Sombre',
    'gen.theme.system': 'Système',
    'gen.primary': 'Couleur Primaire',
    'gen.localization': 'Localisation',
    'gen.localization.desc': 'Définir la langue par défaut.',
    'gen.lang': 'Langue Système',

    'users.title': 'Utilisateurs & Sécurité',
    'users.tab_users': 'Utilisateurs',
    'users.tab_roles': 'Rôles',
    'users.accounts': 'Comptes Utilisateurs',
    'users.accounts_desc': 'Gérer l\'accès au système.',
    'users.add': 'Ajouter Utilisateur',
    'users.edit': 'Éditer Utilisateur',
    'users.new': 'Nouvel Utilisateur',
    'users.save': 'Enregistrer Utilisateur',
    'users.delete_confirm': 'Supprimer l\'utilisateur ?',
    'roles.title': 'Rôles Utilisateurs',
    'roles.desc': 'Définir les ensembles de permissions.',
    'roles.create': 'Créer un Rôle',
    'roles.edit': 'Éditer le Rôle',
    'roles.new': 'Nouveau Rôle',
    'roles.name': 'Nom du Rôle',
    'roles.permissions': 'Permissions',
    'roles.save': 'Enregistrer le Rôle',
    'roles.delete_confirm': 'Supprimer le rôle ?',
    'roles.system': 'Système',

    'schema.title': 'Tables & Schémas',
    'schema.create': 'Créer Table',
    'schema.search': 'Rechercher...',
    'schema.filter_type': 'Filtrer par type',
    'schema.all_types': 'Tous Types',
    'schema.no_results': 'Aucune table ne correspond à vos critères.',
    'schema.basic_info': 'Infos de Base',
    'schema.table_name': 'Nom de la Table',
    'schema.description': 'Description',
    'schema.fields': 'Définitions des Champs',
    'schema.add_field': 'Ajouter un Champ',
    'schema.db_name': 'Nom BDD',
    'schema.label': 'Libellé',
    'schema.type': 'Type',
    'schema.required': 'Requis',
    'schema.sortable': 'Triable',
    'schema.filterable': 'Filtrable',
    'schema.options': 'Options',
    'schema.checked_label': 'Label Coché',
    'schema.unchecked_label': 'Label Décoché',
    'schema.no_fields': 'Aucun champ défini. Cliquez sur "Ajouter un Champ".',
    'schema.data_view': 'Vue Données',
    'schema.enable_data': 'Activer Vue Données',
    'schema.default_data': 'Définir comme Vue par Défaut',
    'schema.allow_non_spatial': 'Autoriser Saisie Non-Spatiale',
    'schema.map_view': 'Couche Carte',
    'schema.enable_map': 'Activer Couche Carte',
    'schema.default_visible': 'Visible par Défaut',
    'schema.geo_type': 'Type Géométrie',
    'schema.color': 'Couleur Couche',
    'schema.interaction': 'Mode Interaction',
    'schema.dialog_size': 'Taille Dialogue',
    'schema.width': 'Largeur',
    'schema.height': 'Hauteur',
    'schema.planning': 'Planification',
    'schema.enable_planning': 'Activer Planification',
    'schema.title_field': 'Champ Titre Événement',
    'schema.start_field': 'Champ Date Début',
    'schema.end_field': 'Champ Date Fin (Optionnel)',
    'schema.default_view': 'Vue par Défaut',
    'schema.timezone': 'Fuseau Horaire',
    'schema.dashboard': 'Tableau de Bord',
    'schema.enable_dashboard': 'Activer Tableau de Bord',
    'schema.dash_title': 'Titre Dashboard',
    'schema.default_dash': 'Définir comme Dashboard par Défaut',
    'schema.show_table': 'Afficher Table de Données sous les graphes',
    'schema.filters': 'Filtres Globaux',
    'schema.add_filter': 'Ajouter Filtre',
    'schema.select_field': 'Choisir Champ',
    'schema.select_value': 'Choisir Valeur',
    'schema.widgets': 'Widgets',
    'schema.add_widget': 'Ajouter Widget',
    'schema.widget_title': 'Titre Widget',
    'schema.preview': 'Aperçu en Direct',
    'schema.override_title': 'Remplacer la Configuration par Défaut ?',
    'schema.override_desc': 'La table est actuellement définie comme défaut.',
    'schema.save': 'Enregistrer Schéma',
    'schema.options_title': 'Gérer Options de Liste',
    'schema.value': 'Valeur (Stockée)',
    'schema.label_disp': 'Libellé (Affiché)',
    'schema.save_list': 'Enregistrer Liste',

    'map.layers': 'Couches',
    'map.visible': 'Couches Visibles',
    'map.editing': 'Édition :',
    'map.select': '-- Choisir Couche --',
    'map.add': 'Ajouter',
    'map.click': 'Cliquez Carte',
    'map.noLayers': 'Aucune couche configurée.',
    'map.adv_search': 'Recherche Avancée',
    'map.target_layer': 'Couche Cible',
    'map.attributes': 'Attributs',
    'map.spatial_filter': 'Filtre Spatial',
    'map.draw_zone': 'Dessiner Zone',
    'map.redraw_zone': 'Redessiner Zone',
    'map.cancel_draw': 'Annuler Dessin',
    'map.zone_active': 'Zone Active',
    'map.results': 'résultats',
    'map.print_title': 'Imprimer Carte',
    'map.format': 'Format & Orientation',
    'map.scale': 'Échelle',
    'map.rotation': 'Rotation',
    'map.export_title': 'Titre',
    'map.export_desc': 'Description (Optionnel)',
    'map.print_btn': 'Imprimer',
    'map.pdf_btn': 'Sauvegarder PDF',
    'map.lat': 'Lat',
    'map.lng': 'Lon',
    'map.new_feature': 'Nouvelle Entité',
    'map.edit_feature': 'Éditer Entité',
    'map.delete_feature': 'Supprimer Entité',
    'map.delete_confirm': 'Êtes-vous sûr de vouloir supprimer cette entité ? Cette action est irréversible.',
    'map.confirm_delete': 'Confirmer Suppression',
    'map.feature_updated': 'Entité Mise à jour',
    'map.feature_added': 'Entité Ajoutée',
    'map.feature_deleted': 'Entité Supprimée',
    'map.export_failed': 'Échec de l\'export',
    'map.import_geojson': 'Importer GeoJSON',
    'map.import_success': 'Importation Réussie',
    'map.import_error': 'Échec de l\'importation',
    'map.import_layer_select': 'Sélectionnez d\'abord une couche cible',
    'map.import_summary': '{count} entités importées',
    'map.import_title': 'Configuration Import',
    'map.import_mode_existing': 'Ajouter à une couche existante',
    'map.import_mode_new': 'Créer une nouvelle couche',
    'map.new_layer_name': 'Nom de la Nouvelle Couche',
    'map.select_file': 'Sélectionner Fichier & Importer',

    'data.tables': 'Tables',
    'data.search': 'Rechercher...',
    'data.add': 'Ajouter',
    'data.noTables': 'Aucune table configurée.',
    'data.select': 'Sélectionnez une table pour voir les données',
    'data.noRecords': 'Aucun enregistrement trouvé.',
    'data.spatial': 'Table Données Spatiales',
    'data.alphanumeric': 'Table Alphanumérique',
    'data.filters': 'Filtres',
    'data.toggle_filters': 'Afficher Filtres Colonnes',
    'data.add_map': 'Ajouter sur Carte',
    'data.add_data': 'Ajouter Donnée Seule',
    'data.clear': 'Effacer',
    'data.showing': 'Affichage',
    'data.to': 'à',
    'data.of': 'sur',
    'data.records': 'enregistrements',
    'data.create': 'Créer Nouvel Enregistrement',
    'data.edit': 'Éditer Enregistrement',
    'data.create_desc': 'Ajouter une nouvelle entrée.',
    'data.edit_desc': 'Mettre à jour les attributs.',
    'data.save': 'Enregistrer',
    'data.delete_title': 'Supprimer Enregistrement',
    'data.delete_desc': 'Êtes-vous sûr de vouloir supprimer cet enregistrement ? Cette action est irréversible.',
    'data.record_deleted': 'Enregistrement Supprimé',
    'data.record_added': 'Enregistrement Ajouté',
    'data.record_updated': 'Enregistrement Mis à jour',
    'data.map_activated': 'Carte Activée',
    'data.go_config': 'Aller à Configuration > Vue Données pour activer les tables.',
    'data.export': 'Exporter',
    'data.export_csv': 'Exporter en CSV',
    'data.export_json': 'Exporter en JSON',
    'data.export_png': 'Exporter en PNG (Capture)',
    'data.export_success': 'Export Réussi',

    'dash.title': 'Analyses & Tableau de Bord',
    'dash.total': 'Total Enr.',
    'dash.fields': 'Champs',
    'dash.widgets': 'Widgets',
    'dash.ai': 'Analyses IA',
    'dash.generate': 'Générer Rapport',
    'dash.noDash': 'Aucun tableau de bord configuré.',
    'dash.select': 'Veuillez sélectionner un jeu de données.',
    'dash.filtered': 'Vue Filtrée',
    'dash.analysis_by': 'Analyse par',
    'dash.no_matches': 'Aucun enregistrement correspondant.',
    'dash.showing_50': 'Affichage des 50 premiers enregistrements.',
    'dash.generate_hint': 'Cliquez sur "Générer Rapport" pour que Gemini analyse vos données.',

    'plan.noPlan': 'Aucune table de planification configurée.',
    'plan.calendars': 'Calendriers',
    'plan.add_event': 'Ajouter Événement',
    'plan.toggle_hint': 'Sélectionnez un calendrier pour changer la visibilité.',
    'plan.select_cal': 'Choisir Calendrier',
    'plan.choose_cal': 'Choisissez dans quel calendrier ajouter cet événement.',
    'plan.hidden': 'Masqué',
    'plan.edit_event': 'Éditer Événement',
    'plan.new_event': 'Nouvel Événement',
    'plan.create_event': 'Créer Événement',
    'plan.update_event': 'Mettre à jour Événement',
    'plan.delete_title': 'Supprimer Événement',
    'plan.delete_desc': 'Êtes-vous sûr de vouloir supprimer cet événement ?',
    'plan.go_config': 'Aller à Configuration > Planification pour activer les tables.',
    'plan.event_created': 'Événement Créé',
    'plan.event_updated': 'Événement Mis à jour',
    'plan.event_deleted': 'Événement Supprimé',
    'plan.calendar_enabled': 'Calendrier Activé',
  },
  es: {
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Crear',
    'common.update': 'Actualizar',
    'common.add': 'Añadir',
    'common.close': 'Cerrar',
    'common.reset': 'Reiniciar',
    'common.done': 'Hecho',
    'common.confirm': 'Confirmar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Info',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.ok': 'OK',

    'nav.map': 'Mapa',
    'nav.data': 'Datos',
    'nav.dash': 'Panel',
    'nav.plan': 'Agenda',
    'nav.config': 'Config',
    'menu.account': 'Mi Cuenta',
    'menu.profile': 'Perfil',
    'menu.settings': 'Configuración',
    'menu.logout': 'Cerrar sesión',
    'profile.title': 'Perfil',
    'profile.subtitle': 'Administra la configuración y preferencias de tu cuenta.',
    'profile.info': 'Información Personal',
    'profile.username': 'Usuario',
    'profile.email': 'Correo',
    'profile.prefs': 'Preferencias',
    'profile.notifs': 'Notificaciones por Correo',
    'profile.notifs_desc': 'Recibir actualizaciones sobre cambios en el sistema.',
    'profile.2fa': 'Autenticación de dos factores',
    'profile.2fa_desc': 'Añadir una capa extra de seguridad.',
    'profile.enabled': 'Habilitado',
    'profile.enable': 'Habilitar',

    'login.title': 'GeoNexus SIG',
    'login.subtitle': 'Plataforma de Gestión de Datos Espaciales',
    'login.welcome': 'Bienvenido',
    'login.instruction': 'Inicia sesión para continuar',
    'login.username': 'Usuario',
    'login.password': 'Contraseña',
    'login.btn': 'Iniciar sesión',
    'login.authenticating': 'Autenticando...',
    'login.error': 'Credenciales inválidas. Intenta de nuevo.',
    
    'cfg.title': 'Configuración',
    'cfg.tables': 'Tablas y Esquemas',
    'cfg.map': 'Capas del Mapa',
    'cfg.data': 'Vistas de Datos',
    'cfg.plan': 'Planificación',
    'cfg.dash': 'Paneles',
    'cfg.users': 'Usuarios y Seguridad',
    'cfg.shortcuts': 'Atajos',
    'cfg.general': 'Ajustes Generales',

    'shortcuts.title': 'Atajos',
    'shortcuts.subtitle': 'Acciones rápidas accesibles desde la barra lateral.',
    'shortcuts.add': 'Añadir Atajo',
    'shortcuts.edit': 'Editar Atajo',
    'shortcuts.new': 'Nuevo Atajo',
    'shortcuts.name': 'Nombre',
    'shortcuts.icon': 'Icono',
    'shortcuts.color': 'Color',
    'shortcuts.type': 'Tipo',
    'shortcuts.config': 'Configuración',
    'shortcuts.no_config': 'No hay atajos configurados.',
    'shortcuts.quick_actions': 'Acciones Rápidas',

    'gen.title': 'Ajustes Generales',
    'gen.desc': 'Personaliza la apariencia y comportamiento de la aplicación.',
    'gen.appearance': 'Apariencia',
    'gen.appearance.desc': 'Gestionar tema y colores.',
    'gen.theme': 'Modo Tema',
    'gen.theme.light': 'Claro',
    'gen.theme.dark': 'Oscuro',
    'gen.theme.system': 'Sistema',
    'gen.primary': 'Color Primario',
    'gen.localization': 'Localización',
    'gen.localization.desc': 'Establecer idioma por defecto.',
    'gen.lang': 'Idioma del Sistema',

    'users.title': 'Usuarios y Seguridad',
    'users.tab_users': 'Usuarios',
    'users.tab_roles': 'Roles',
    'users.accounts': 'Cuentas de Usuario',
    'users.accounts_desc': 'Gestionar acceso al sistema.',
    'users.add': 'Añadir Usuario',
    'users.edit': 'Editar Usuario',
    'users.new': 'Nuevo Usuario',
    'users.save': 'Guardar Usuario',
    'users.delete_confirm': '¿Eliminar usuario?',
    'roles.title': 'Roles de Usuario',
    'roles.desc': 'Definir conjuntos de permisos.',
    'roles.create': 'Crear Rol',
    'roles.edit': 'Editar Rol',
    'roles.new': 'Nuevo Rol',
    'roles.name': 'Nombre del Rol',
    'roles.permissions': 'Permisos',
    'roles.save': 'Guardar Rol',
    'roles.delete_confirm': '¿Eliminar rol?',
    'roles.system': 'Sistema',

    'schema.title': 'Tablas y Esquemas',
    'schema.create': 'Crear Tabla',
    'schema.search': 'Buscar tablas...',
    'schema.filter_type': 'Filtrar por tipo',
    'schema.all_types': 'Todos los Tipos',
    'schema.no_results': 'No se encontraron tablas.',
    'schema.basic_info': 'Info Básica',
    'schema.table_name': 'Nombre Tabla',
    'schema.description': 'Descripción',
    'schema.fields': 'Definiciones de Campos',
    'schema.add_field': 'Añadir Campo',
    'schema.db_name': 'Nombre BD',
    'schema.label': 'Etiqueta',
    'schema.type': 'Tipo',
    'schema.required': 'Requerido',
    'schema.sortable': 'Ordenable',
    'schema.filterable': 'Filtrable',
    'schema.options': 'Opciones',
    'schema.checked_label': 'Etiqueta Marcada',
    'schema.unchecked_label': 'Etiqueta Desmarcada',
    'schema.no_fields': 'No hay campos definidos.',
    'schema.data_view': 'Vista de Datos',
    'schema.enable_data': 'Habilitar Vista Datos',
    'schema.default_data': 'Establecer como Vista por Defecto',
    'schema.allow_non_spatial': 'Permitir Entrada No Espacial',
    'schema.map_view': 'Capa de Mapa',
    'schema.enable_map': 'Habilitar Capa Mapa',
    'schema.default_visible': 'Visible por Defecto',
    'schema.geo_type': 'Tipo Geometría',
    'schema.color': 'Color Capa',
    'schema.interaction': 'Modo Interacción',
    'schema.dialog_size': 'Tamaño Diálogo',
    'schema.width': 'Ancho',
    'schema.height': 'Alto',
    'schema.planning': 'Planificación',
    'schema.enable_planning': 'Habilitar Planificación',
    'schema.title_field': 'Campo Título Evento',
    'schema.start_field': 'Campo Fecha Inicio',
    'schema.end_field': 'Campo Fecha Fin (Opcional)',
    'schema.default_view': 'Vista por Defecto',
    'schema.timezone': 'Zona Horaria',
    'schema.dashboard': 'Panel',
    'schema.enable_dashboard': 'Habilitar Panel',
    'schema.dash_title': 'Título Panel',
    'schema.default_dash': 'Establecer como Panel por Defecto',
    'schema.show_table': 'Mostrar Tabla de Datos bajo gráficos',
    'schema.filters': 'Filtros Globales',
    'schema.add_filter': 'Añadir Filtro',
    'schema.select_field': 'Seleccionar Campo',
    'schema.select_value': 'Seleccionar Valor',
    'schema.widgets': 'Widgets',
    'schema.add_widget': 'Añadir Widget',
    'schema.widget_title': 'Título Widget',
    'schema.preview': 'Vista Previa',
    'schema.override_title': '¿Sobrescribir configuración por defecto?',
    'schema.override_desc': 'La tabla está configurada como predeterminada.',
    'schema.save': 'Guardar Esquema',
    'schema.options_title': 'Gestionar Opciones',
    'schema.value': 'Valor (Guardado)',
    'schema.label_disp': 'Etiqueta (Mostrada)',
    'schema.save_list': 'Guardar Lista',

    'map.layers': 'Capas',
    'map.visible': 'Capas Visibles',
    'map.editing': 'Editando:',
    'map.select': '-- Seleccionar Capa --',
    'map.add': 'Añadir',
    'map.click': 'Clic en Mapa',
    'map.noLayers': 'No hay capas configuradas.',
    'map.adv_search': 'Búsqueda Avanzada',
    'map.target_layer': 'Capa Objetivo',
    'map.attributes': 'Atributos',
    'map.spatial_filter': 'Filtro Espacial',
    'map.draw_zone': 'Dibujar Zona',
    'map.redraw_zone': 'Redibujar Zona',
    'map.cancel_draw': 'Cancelar Dibujo',
    'map.zone_active': 'Zona Activa',
    'map.results': 'resultados',
    'map.print_title': 'Imprimir Mapa',
    'map.format': 'Formato y Orientación',
    'map.scale': 'Escala',
    'map.rotation': 'Rotación',
    'map.export_title': 'Título',
    'map.export_desc': 'Descripción (Opcional)',
    'map.print_btn': 'Imprimir',
    'map.pdf_btn': 'Guardar PDF',
    'map.lat': 'Lat',
    'map.lng': 'Lon',
    'map.new_feature': 'Nueva Entidad',
    'map.edit_feature': 'Editar Entidad',
    'map.delete_feature': 'Eliminar Entidad',
    'map.delete_confirm': '¿Estás seguro de que quieres eliminar esta entidad? Esta acción no se puede deshacer.',
    'map.confirm_delete': 'Confirmar Eliminación',
    'map.feature_updated': 'Entidad Actualizada',
    'map.feature_added': 'Entidad Añadida',
    'map.feature_deleted': 'Entidad Eliminada',
    'map.export_failed': 'Fallo al exportar',
    'map.import_geojson': 'Importar GeoJSON',
    'map.import_success': 'Importación Exitosa',
    'map.import_error': 'Fallo en la importación',
    'map.import_layer_select': 'Selecciona primero una capa de destino',
    'map.import_summary': '{count} entidades importadas',
    'map.import_title': 'Configuración de Importación',
    'map.import_mode_existing': 'Añadir a capa existente',
    'map.import_mode_new': 'Crear nueva capa',
    'map.new_layer_name': 'Nombre de Nueva Capa',
    'map.select_file': 'Seleccionar Archivo e Importar',

    'data.tables': 'Tablas',
    'data.search': 'Buscar...',
    'data.add': 'Añadir',
    'data.noTables': 'No hay tablas configuradas.',
    'data.select': 'Selecciona una tabla para ver datos',
    'data.noRecords': 'No se encontraron registros.',
    'data.spatial': 'Tabla de Datos Espaciales',
    'data.alphanumeric': 'Tabla Alfanumérica',
    'data.filters': 'Filtros',
    'data.toggle_filters': 'Alternar Filtros de Columna',
    'data.add_map': 'Añadir en Mapa',
    'data.add_data': 'Añadir Solo Datos',
    'data.clear': 'Limpiar',
    'data.showing': 'Mostrando',
    'data.to': 'a',
    'data.of': 'de',
    'data.records': 'registros',
    'data.create': 'Crear Nuevo Registro',
    'data.edit': 'Editar Registro',
    'data.create_desc': 'Añadir una nueva entrada.',
    'data.edit_desc': 'Actualizar atributos.',
    'data.save': 'Guardar Cambios',
    'data.delete_title': 'Eliminar Registro',
    'data.delete_desc': '¿Estás seguro de que quieres eliminar este registro? Esta acción no se puede deshacer.',
    'data.record_deleted': 'Registro Eliminado',
    'data.record_added': 'Registro Añadido',
    'data.record_updated': 'Registro Actualizado',
    'data.map_activated': 'Mapa Activado',
    'data.go_config': 'Ir a Configuración > Vista de Datos para habilitar tablas.',
    'data.export': 'Exportar',
    'data.export_csv': 'Exportar como CSV',
    'data.export_json': 'Exportar como JSON',
    'data.export_png': 'Exportar como PNG',
    'data.export_success': 'Exportación Exitosa',

    'dash.title': 'Panel y Análisis',
    'dash.total': 'Total Reg.',
    'dash.fields': 'Campos',
    'dash.widgets': 'Widgets',
    'dash.ai': 'Perspectivas IA',
    'dash.generate': 'Generar Informe',
    'dash.noDash': 'No hay paneles configurados.',
    'dash.select': 'Por favor selecciona un conjunto de datos.',
    'dash.filtered': 'Vista Filtrada',
    'dash.analysis_by': 'Análisis por',
    'dash.no_matches': 'No hay registros que coincidan.',
    'dash.showing_50': 'Mostrando los primeros 50 registros.',
    'dash.generate_hint': 'Haz clic en "Generar Informe" para que Gemini analice tus datos.',

    'plan.noPlan': 'No hay tablas de planificación configuradas.',
    'plan.calendars': 'Calendarios',
    'plan.add_event': 'Añadir Evento',
    'plan.toggle_hint': 'Selecciona un calendario para cambiar visibilidad.',
    'plan.select_cal': 'Seleccionar Calendario',
    'plan.choose_cal': 'Elige en qué calendario añadir este evento.',
    'plan.hidden': 'Oculto',
    'plan.edit_event': 'Editar Evento',
    'plan.new_event': 'Nuevo Evento',
    'plan.create_event': 'Crear Evento',
    'plan.update_event': 'Actualizar Evento',
    'plan.delete_title': 'Eliminar Evento',
    'plan.delete_desc': '¿Estás seguro de que quieres eliminar este evento?',
    'plan.go_config': 'Ir a Configuración > Planificación para habilitar tablas.',
    'plan.event_created': 'Evento Creado',
    'plan.event_updated': 'Evento Actualizado',
    'plan.event_deleted': 'Evento Eliminado',
    'plan.calendar_enabled': 'Calendario Habilitado',
  },
  de: {
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.add': 'Hinzufügen',
    'common.close': 'Schließen',
    'common.reset': 'Zurücksetzen',
    'common.done': 'Fertig',
    'common.confirm': 'Bestätigen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.warning': 'Warnung',
    'common.info': 'Info',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.ok': 'OK',

    'nav.map': 'Karte',
    'nav.data': 'Daten',
    'nav.dash': 'Dashboard',
    'nav.plan': 'Planung',
    'nav.config': 'Konfig',
    'menu.account': 'Mein Konto',
    'menu.profile': 'Profil',
    'menu.settings': 'Einstellungen',
    'menu.logout': 'Abmelden',
    'profile.title': 'Profil',
    'profile.subtitle': 'Verwalten Sie Ihre Kontoeinstellungen und Präferenzen.',
    'profile.info': 'Persönliche Informationen',
    'profile.username': 'Benutzername',
    'profile.email': 'E-Mail',
    'profile.prefs': 'Präferenzen',
    'profile.notifs': 'E-Mail-Benachrichtigungen',
    'profile.notifs_desc': 'Erhalten Sie Updates über Systemänderungen.',
    'profile.2fa': 'Zwei-Faktor-Authentifizierung',
    'profile.2fa_desc': 'Fügen Sie eine zusätzliche Sicherheitsebene hinzu.',
    'profile.enabled': 'Aktiviert',
    'profile.enable': 'Aktivieren',

    'login.title': 'GeoNexus GIS',
    'login.subtitle': 'Plattform für Geodatenmanagement',
    'login.welcome': 'Willkommen zurück',
    'login.instruction': 'Bitte melden Sie sich an, um fortzufahren',
    'login.username': 'Benutzername',
    'login.password': 'Passwort',
    'login.btn': 'Anmelden',
    'login.authenticating': 'Anmelden...',
    'login.error': 'Ungültige Anmeldeinformationen. Bitte versuchen Sie es erneut.',
    
    'cfg.title': 'Konfiguration',
    'cfg.tables': 'Tabellen & Schemata',
    'cfg.map': 'Kartenebenen',
    'cfg.data': 'Datenansichten',
    'cfg.plan': 'Planung',
    'cfg.dash': 'Dashboards',
    'cfg.users': 'Benutzer & Sicherheit',
    'cfg.shortcuts': 'Verknüpfungen',
    'cfg.general': 'Allgemeine Einstellungen',

    'shortcuts.title': 'Verknüpfungen',
    'shortcuts.subtitle': 'Schnellaktionen, die über die Seitenleiste zugänglich sind.',
    'shortcuts.add': 'Verknüpfung hinzufügen',
    'shortcuts.edit': 'Verknüpfung bearbeiten',
    'shortcuts.new': 'Neue Verknüpfung',
    'shortcuts.name': 'Name',
    'shortcuts.icon': 'Symbol',
    'shortcuts.color': 'Farbe',
    'shortcuts.type': 'Typ',
    'shortcuts.config': 'Konfiguration',
    'shortcuts.no_config': 'Keine Verknüpfungen konfiguriert.',
    'shortcuts.quick_actions': 'Schnellaktionen',

    'gen.title': 'Allgemeine Einstellungen',
    'gen.desc': 'Passen Sie das Erscheinungsbild und Verhalten der Anwendung an.',
    'gen.appearance': 'Erscheinungsbild',
    'gen.appearance.desc': 'Thema und Branding-Farben verwalten.',
    'gen.theme': 'Design-Modus',
    'gen.theme.light': 'Hell',
    'gen.theme.dark': 'Dunkel',
    'gen.theme.system': 'System',
    'gen.primary': 'Primärfarbe',
    'gen.localization': 'Lokalisierung',
    'gen.localization.desc': 'Standardsprache festlegen.',
    'gen.lang': 'Systemsprache',

    'users.title': 'Benutzer & Sicherheit',
    'users.tab_users': 'Benutzer',
    'users.tab_roles': 'Rollen',
    'users.accounts': 'Benutzerkonten',
    'users.accounts_desc': 'Systemzugriff verwalten.',
    'users.add': 'Benutzer hinzufügen',
    'users.edit': 'Benutzer bearbeiten',
    'users.new': 'Neuer Benutzer',
    'users.save': 'Benutzer speichern',
    'users.delete_confirm': 'Benutzer löschen?',
    'roles.title': 'Benutzerrollen',
    'roles.desc': 'Berechtigungssätze definieren.',
    'roles.create': 'Rolle erstellen',
    'roles.edit': 'Rolle bearbeiten',
    'roles.new': 'Neue Rolle',
    'roles.name': 'Rollenname',
    'roles.permissions': 'Berechtigungen',
    'roles.save': 'Rolle speichern',
    'roles.delete_confirm': 'Rolle löschen?',
    'roles.system': 'System',

    'schema.title': 'Tabellen & Schemata',
    'schema.create': 'Tabelle erstellen',
    'schema.search': 'Tabellen suchen...',
    'schema.filter_type': 'Nach Typ filtern',
    'schema.all_types': 'Alle Typen',
    'schema.no_results': 'Keine Tabellen gefunden.',
    'schema.basic_info': 'Basisinfo',
    'schema.table_name': 'Tabellenname',
    'schema.description': 'Beschreibung',
    'schema.fields': 'Felddefinitionen',
    'schema.add_field': 'Feld hinzufügen',
    'schema.db_name': 'DB Name',
    'schema.label': 'Beschriftung',
    'schema.type': 'Typ',
    'schema.required': 'Erforderlich',
    'schema.sortable': 'Sortierbar',
    'schema.filterable': 'Filterbar',
    'schema.options': 'Optionen',
    'schema.checked_label': 'Markiertes Label',
    'schema.unchecked_label': 'Unmarkiertes Label',
    'schema.no_fields': 'Keine Felder definiert.',
    'schema.data_view': 'Datenansicht',
    'schema.enable_data': 'Datenansicht aktivieren',
    'schema.default_data': 'Als Standard-Datenansicht festlegen',
    'schema.allow_non_spatial': 'Nicht-räumliche Eingabe erlauben',
    'schema.map_view': 'Kartenebene',
    'schema.enable_map': 'Kartenebene aktivieren',
    'schema.default_visible': 'Standardmäßig sichtbar',
    'schema.geo_type': 'Geometrietyp',
    'schema.color': 'Ebenenfarbe',
    'schema.interaction': 'Interaktionsmodus',
    'schema.dialog_size': 'Dialoggröße',
    'schema.width': 'Breite',
    'schema.height': 'Höhe',
    'schema.planning': 'Planung',
    'schema.enable_planning': 'Planung aktivieren',
    'schema.title_field': 'Ereignistitel-Feld',
    'schema.start_field': 'Startdatum-Feld',
    'schema.end_field': 'Enddatum-Feld (Optional)',
    'schema.default_view': 'Standardansicht',
    'schema.timezone': 'Zeitzone',
    'schema.dashboard': 'Dashboard',
    'schema.enable_dashboard': 'Dashboard aktivieren',
    'schema.dash_title': 'Dashboard-Titel',
    'schema.default_dash': 'Als Standard-Dashboard festlegen',
    'schema.show_table': 'Datentabelle unter Diagrammen anzeigen',
    'schema.filters': 'Globale Dashboard-Filter',
    'schema.add_filter': 'Filter hinzufügen',
    'schema.select_field': 'Feld auswählen',
    'schema.select_value': 'Wert auswählen',
    'schema.widgets': 'Widgets',
    'schema.add_widget': 'Widget hinzufügen',
    'schema.widget_title': 'Widget-Titel',
    'schema.preview': 'Live-Vorschau',
    'schema.override_title': 'Standardkonfiguration überschreiben?',
    'schema.override_desc': 'Die Tabelle ist derzeit als Standard festgelegt.',
    'schema.save': 'Schema speichern',
    'schema.options_title': 'Listenoptionen verwalten',
    'schema.value': 'Wert (Gespeichert)',
    'schema.label_disp': 'Beschriftung (Angezeigt)',
    'schema.save_list': 'Liste speichern',

    'map.layers': 'Ebenen',
    'map.visible': 'Sichtbare Ebenen',
    'map.editing': 'Bearbeitung:',
    'map.select': '-- Ebene wählen --',
    'map.add': 'Hinzufügen',
    'map.click': 'Klick Karte',
    'map.noLayers': 'Keine Kartenebenen konfiguriert.',
    'map.adv_search': 'Erweiterte Suche',
    'map.target_layer': 'Zielebene',
    'map.attributes': 'Attribute',
    'map.spatial_filter': 'Räumlicher Filter',
    'map.draw_zone': 'Zone zeichnen',
    'map.redraw_zone': 'Zone neu zeichnen',
    'map.cancel_draw': 'Zeichnen abbrechen',
    'map.zone_active': 'Zone aktiv',
    'map.results': 'Ergebnisse',
    'map.print_title': 'Karte drucken',
    'map.format': 'Format & Ausrichtung',
    'map.scale': 'Maßstab',
    'map.rotation': 'Drehung',
    'map.export_title': 'Titel',
    'map.export_desc': 'Beschreibung (Optional)',
    'map.print_btn': 'Drucken',
    'map.pdf_btn': 'PDF speichern',
    'map.lat': 'Lat',
    'map.lng': 'Lon',
    'map.new_feature': 'Neues Feature',
    'map.edit_feature': 'Feature bearbeiten',
    'map.delete_feature': 'Feature löschen',
    'map.delete_confirm': 'Möchten Sie dieses Feature wirklich löschen? Dies kann nicht rückgängig gemacht werden.',
    'map.confirm_delete': 'Löschen bestätigen',
    'map.feature_updated': 'Feature aktualisiert',
    'map.feature_added': 'Feature hinzugefügt',
    'map.feature_deleted': 'Feature gelöscht',
    'map.export_failed': 'Export fehlgeschlagen',
    'map.import_geojson': 'GeoJSON importieren',
    'map.import_success': 'Import erfolgreich',
    'map.import_error': 'Import fehlgeschlagen',
    'map.import_layer_select': 'Bitte wählen Sie zuerst eine Zielebene',
    'map.import_summary': '{count} Features importiert',
    'map.import_title': 'Importkonfiguration',
    'map.import_mode_existing': 'Zu bestehender Ebene hinzufügen',
    'map.import_mode_new': 'Neue Ebene erstellen',
    'map.new_layer_name': 'Neuer Ebenenname',
    'map.select_file': 'Datei wählen & Importieren',

    'data.tables': 'Tabellen',
    'data.search': 'Suchen...',
    'data.add': 'Hinzufügen',
    'data.noTables': 'Keine Tabellen konfiguriert.',
    'data.select': 'Wählen Sie eine Tabelle aus',
    'data.noRecords': 'Keine Datensätze gefunden.',
    'data.spatial': 'Räumliche Datentabelle',
    'data.alphanumeric': 'Alphanumerische Tabelle',
    'data.filters': 'Filter',
    'data.toggle_filters': 'Spaltenfilter umschalten',
    'data.add_map': 'Auf Karte hinzufügen',
    'data.add_data': 'Nur Daten hinzufügen',
    'data.clear': 'Leeren',
    'data.showing': 'Zeige',
    'data.to': 'bis',
    'data.of': 'von',
    'data.records': 'Datensätzen',
    'data.create': 'Neuen Datensatz erstellen',
    'data.edit': 'Datensatz bearbeiten',
    'data.create_desc': 'Einen neuen Eintrag hinzufügen.',
    'data.edit_desc': 'Attribute aktualisieren.',
    'data.save': 'Änderungen speichern',
    'data.delete_title': 'Datensatz löschen',
    'data.delete_desc': 'Möchten Sie diesen Datensatz wirklich löschen? Dies kann nicht rückgängig gemacht werden.',
    'data.record_deleted': 'Datensatz gelöscht',
    'data.record_added': 'Datensatz hinzugefügt',
    'data.record_updated': 'Datensatz aktualisiert',
    'data.map_activated': 'Karte aktiviert',
    'data.go_config': 'Gehen Sie zu Konfiguration > Datenansicht, um Tabellen zu aktivieren.',
    'data.export': 'Exportieren',
    'data.export_csv': 'Als CSV exportieren',
    'data.export_json': 'Als JSON exportieren',
    'data.export_png': 'Als PNG exportieren',
    'data.export_success': 'Export erfolgreich',

    'dash.title': 'Analyse & Dashboard',
    'dash.total': 'Gesamt',
    'dash.fields': 'Felder',
    'dash.widgets': 'Widgets',
    'dash.ai': 'KI-Einblicke',
    'dash.generate': 'Bericht generieren',
    'dash.noDash': 'Keine Dashboards konfiguriert.',
    'dash.select': 'Bitte wählen Sie einen Datensatz aus.',
    'dash.filtered': 'Gefilterte Ansicht',
    'dash.analysis_by': 'Analyse nach',
    'dash.no_matches': 'Keine passenden Datensätze.',
    'dash.showing_50': 'Zeige die ersten 50 Datensätze.',
    'dash.generate_hint': 'Klicken Sie auf "Bericht generieren", um Ihre Daten von Gemini analysieren zu lassen.',

    'plan.noPlan': 'Keine Planungstabellen konfiguriert.',
    'plan.calendars': 'Kalender',
    'plan.add_event': 'Ereignis hinzufügen',
    'plan.toggle_hint': 'Wählen Sie einen Kalender, um die Sichtbarkeit umzuschalten.',
    'plan.select_cal': 'Kalender auswählen',
    'plan.choose_cal': 'Wählen Sie, zu welchem Kalender dieses Ereignis hinzugefügt werden soll.',
    'plan.hidden': 'Versteckt',
    'plan.edit_event': 'Ereignis bearbeiten',
    'plan.new_event': 'Neues Ereignis',
    'plan.create_event': 'Ereignis erstellen',
    'plan.update_event': 'Ereignis aktualisieren',
    'plan.delete_title': 'Ereignis löschen',
    'plan.delete_desc': 'Möchten Sie dieses Ereignis wirklich löschen?',
    'plan.go_config': 'Gehen Sie zu Konfiguration > Planung, um Tabellen zu aktivieren.',
    'plan.event_created': 'Ereignis erstellt',
    'plan.event_updated': 'Ereignis aktualisiert',
    'plan.event_deleted': 'Ereignis gelöscht',
    'plan.calendar_enabled': 'Kalender aktiviert',
  }
};
